services:
  backend:
    image: backend-proyecto 
    ports:
      - "8000:8000"
    networks:
      - app_network

  frontend:
    image: frontend-proyecto
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
